### ISSUE TITLE
Telegram integration

### ISSUE THREAD

**Issue by wilsonwid** [RussellDash332/pancake#3]
[https://github.com/appleboy/telegram-action](https://github.com/appleboy/telegram-action) might be useful, as well as [https://docs.github.com/en/actions/security-guides/encrypted-secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) for managing secrets on GitHub.

**Comment by RussellDash332** [comment]
Thanks for the issue! It's on the to-do list so do stay tuned!

**Comment by RussellDash332** [comment]
The lazy me did the whole thing right under the main branch so I'll mark this issue as resolved
